### PR TITLE
add new paper to Video Grounding (Activity Localization) using Natura…

### PR DESCRIPTION
**Pull request by yufansong**
I add some new papers to Video Grounding (Activity Localization) using Natural Language part.
I am focusing on this task. Maybe I will continue to add more papers about this area.
It is interesting to find you and Jiyang Gao are advised by the same advisor. It is so cool.

### CODE REVIEW

**Comment by TheShadow29** [comment]
Great. Thanks. I am slightly occupied, but I will definitely get back to updating the papers (hopefully by Tuesday).

Thank you for your patience.

**Comment by TheShadow29** [comment]
@yufansong  All the papers look very relevant. Could you just capitalize `paper`? I can then merge it.

**Comment by yufansong** [comment]
I already capitalize the paper.

**Comment by TheShadow29** [comment]
Whoops, I meant `paper` -> `Paper` (sorry for the confusion).

**Comment by yufansong** [comment]
Sorry, my fault. I revised it again.

**Comment by TheShadow29** [comment]
Great. Thanks a lot for your contribution!

**Pull request merged**
